apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-archive-pvc
  namespace: a2a-samples-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi