apiVersion: fusion.tuna.ai/v1
kind: AgentDeployment
metadata:
  name: travel-advisor-deploy
  namespace: a2a-samples-ns
spec:
  agentCard:
    name: travel-advisor
    description: A simple agent that can make plan about your trips.
    capabilities:
      streaming: true
      pushNotifications: false
      stateTransitionHistory: false
    defaultInputModes:
      - "text/plain"
      - "application/json"
    defaultOutputModes:
      - "application/json"
      - "image/png"
    skills:
      - description: "Travel planner"
        id: travel_planner
        name: travel planner
        tags:
          - travel planner
    provider:
      organization: tuna
      url: https://github.com/tuna-headquater/tuna-fusion-agent-samples
    version: "1.0.0"
  environmentName: a2a-samples-env
  git:
    watchedBranchName: "refs/heads/main"
  a2a:
    queueManager:
      provider: InMemory
    taskStore:
      provider: InMemory
  entrypoint: executor.TravelPlannerAgentExecutor
  fileAssets:
#    configuration that uses openai/gpt-oss-20b service on docker host
    - executable: false
      fileName: config.json
      targetDirectory: DEPLOY_ARCHIVE
      content: |-
        {
          "model_name": "openai/gpt-oss-20b",
          "base_url": "http://host.docker.internal:8000/v1",
          "api_key": "lm-studio"
        }
